CREATE TABLE `twii_user` (
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`username` VARCHAR( 100 ) NOT NULL ,
	`email` VARCHAR( 100 ) NOT NULL ,
	`password` VARCHAR( 8 ) NOT NULL
) ENGINE = MYISAM ;
